project_id = "xiphdrbatfbgcjmizcdu"

[functions]
  [functions.analyze-meal]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
